-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", disabled = true })
hl.monitor({ output = "DP-4", mode = "1920x1080@60.00", position = "5600x0", scale = 1.00 })
hl.monitor({ output = "DP-6", mode = "1920x1080@74.97", position = "3680x0", scale = 1.00 })
hl.monitor({ output = "DP-3", mode = "1920x1080@74.97", position = "1760x32", scale = 1.00 })
